version: "3.8"

services:
  srs:
    image: ossrs/srs:5
    container_name: srs_aoe
    restart: always
    ports:
      - "1935:1935"
      - "8080:8080"
      - "1985:1985"
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf
      - /home/playback/record:/usr/local/srs/objs/nginx/html/record
      - /home/playback/live:/usr/local/srs/objs/nginx/html/live
    command: ["./objs/srs", "-c", "conf/srs.conf"]
  web:
    build: .
    container_name: web_aoe
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /home/playback/record:/usr/local/srs/objs/nginx/html/record
      - /home/playback/live:/usr/local/srs/objs/nginx/html/live
    environment:
      - RECORD_DIR=/usr/local/srs/objs/nginx/html/record
      - LIVE_DIR=/usr/local/srs/objs/nginx/html/live
      - SRS_HOST=srs_aoe
      - SRS_HTTP_PORT=8080
    depends_on:
      - srs
