listen              1935;
max_connections     1000;
daemon              off;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}

vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_path        /usr/local/srs/objs/nginx/html/live;
        hls_fragment    5;
        hls_window      30;
    }
    
    dvr {
        enabled         on;
        dvr_apply       all;
        dvr_path        /usr/local/srs/objs/nginx/html/record/[app]/[stream]/[2006]-[01]-[02]/[15]-[04]-[05].mp4;
        dvr_plan        segment;
        dvr_duration    60;
        dvr_wait_keyframe on;
        time_jitter     full;
    }
}
