import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';
import cors from 'cors';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const port = process.env.PORT || 3000;
const RECORD_DIR = process.env.RECORD_DIR || '/usr/local/srs/objs/nginx/html/record';
const LIVE_DIR = process.env.LIVE_DIR || '/usr/local/srs/objs/nginx/html/live';

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, '../dist')));
app.use('/record', express.static(RECORD_DIR));
app.use('/live', express.static(LIVE_DIR));

const NAMES_FILE = path.join(RECORD_DIR, 'machine_names.json');

// Get custom machine names
app.get('/api/machine-names', (req, res) => {
    if (!fs.existsSync(NAMES_FILE)) {
        return res.json({});
    }
    try {
        const data = fs.readFileSync(NAMES_FILE, 'utf8');
        res.json(JSON.parse(data));
    } catch (err) {
        res.status(500).json({ error: 'Failed to read names' });
    }
});

// Save custom machine names
app.post('/api/machine-names', (req, res) => {
    try {
        const names = req.body;
        fs.writeFileSync(NAMES_FILE, JSON.stringify(names, null, 2));
        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: 'Failed to save names' });
    }
});

// Proxy for SRS Status to avoid mixed content
app.get('/api/srs-streams', async (req, res) => {
    try {
        const response = await fetch('http://192.168.9.214:1985/api/v1/streams');
        const data = await response.json();
        res.json(data);
    } catch (err) {
        res.status(500).json({ error: 'SRS API not reachable' });
    }
});

// Helper to scan for recordings (Now looks for M3U8 generated by HLS DVR)
app.get('/api/recordings/:machineId', (req, res) => {
    const { machineId } = req.params;
    const machinePath = path.join(RECORD_DIR, 'live', 'live', machineId);

    if (!fs.existsSync(machinePath)) {
        return res.json([]);
    }

    try {
        // Files are now .m3u8 playlists named by date (YYYY-MM-DD.m3u8)
        const entries = fs.readdirSync(machinePath);
        const recordings = entries
            .filter(f => f.endsWith('.m3u8'))
            .map(f => {
                const dateString = f.replace('.m3u8', '');
                return {
                    id: dateString,
                    date: dateString,
                    title: `Video toàn ngày ${dateString}`,
                    time: `Full Day Playback`,
                    url: `/record/live/live/${machineId}/${f}`,
                    playlist: [] // Not needed since the m3u8 IS the playlist
                };
            });

        res.json(recordings.sort((a,b) => b.date.localeCompare(a.date)));
    } catch (err) {
        console.error(err);
        res.status(500).json({ error: 'Failed to scan recordings' });
    }
});

app.use((req, res) => {
    res.sendFile(path.join(__dirname, '../dist/index.html'));
});

app.listen(port, () => {
    console.log(`Web server listening on port ${port}`);
});
