server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy HLS streams from SRS (Both live and default app)
    location /live/ {
        proxy_pass http://srs:8080;
        add_header Cache-Control no-cache;
        add_header Access-Control-Allow-Origin *;
    }

    location /__defaultApp__/ {
        proxy_pass http://srs:8080;
        add_header Cache-Control no-cache;
        add_header Access-Control-Allow-Origin *;
    }

    # Proxy API and replays from Worker
    location /api/v1/ {
        proxy_pass http://worker:5000/api/v1/;
    }

    location /replays/ {
        alias /data/;
        add_header Cache-Control no-cache;
        add_header Access-Control-Allow-Origin *;
    }
}
